import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import Rbf
from Hyper_utils import plot_disp, plot_relative_error, createFolder

#region Save path       
originalDir = os.path.dirname(os.path.abspath(__file__))
print('current working directory is ' + originalDir)
os.chdir(os.path.join(originalDir))

foldername = 'MSE_error_hyper_results'  
createFolder(foldername )
os.chdir(os.path.join(originalDir, './'+ foldername + '/')) 

originalDir_real = os.path.join(originalDir, './'+ foldername + '/')

os.chdir(os.path.join(originalDir, './'+ 'FE_full_square_hyper_one_traction_ground_truth' + '/'))
# load the ground truth data generated by FEM in full sqaure 
U1_FE = np.loadtxt('U_in ts=4 .txt')
V1_FE = np.loadtxt('V_in ts=4 .txt')
U_FE, V_FE = np.loadtxt('u ts=4 .txt'), np.loadtxt('v ts=4 .txt')
s_xx_1, s_xy_1, s_yy_1 = np.loadtxt('s_xx_in ts=4 .txt'), np.loadtxt('s_xy_in ts=4 .txt'), np.loadtxt('s_yy_in ts=4 .txt')
s_xx, s_xy, s_yy = np.loadtxt('s_xx ts=4 .txt'), np.loadtxt('s_xy ts=4 .txt'), np.loadtxt('s_yy ts=4 .txt')
X1_FE, Y1_FE = np.loadtxt('X1.txt'), np.loadtxt('Y1.txt')
X_FE, Y_FE = np.loadtxt('X.txt'), np.loadtxt('Y.txt')


os.chdir(os.path.join(originalDir, './'+ 'FE_DeepONet_hyper_elasticity_quasi_static_coupling_results' + '/'))

U1_NO, V1_NO = np.loadtxt('u2 ts=4 .txt'), np.loadtxt('v2 ts=4 .txt')
U_NO, V_NO = np.loadtxt('u ts=4 .txt'), np.loadtxt('v ts=4 .txt')
s_xx_1_NO, s_xy_1_NO, s_yy_1_NO = np.loadtxt('sigma_xx2 ts=4.txt'), np.loadtxt('sigma_xy2 ts=4.txt'), np.loadtxt('sigma_yy2 ts=4.txt')
X_NO, Y_NO = np.loadtxt('X.txt'), np.loadtxt('Y.txt')
X1_NO, Y1_NO = np.loadtxt('X1.txt'), np.loadtxt('Y1.txt')
error_list_FE_NO = np.loadtxt('error_list_FE_NN_hyper ts=4 iter=16.txt')

os.chdir(os.path.join(originalDir, './'+ 'FE_FE_hyper_elasticity_quasi_static_coupling_results' + '/'))

U1_FE_FE, V1_FE_FE = np.loadtxt('u2 ts=4 .txt'), np.loadtxt('v2 ts=4 .txt')
U_FE_FE, V_FE_FE = np.loadtxt('u ts=4 .txt'), np.loadtxt('v ts=4 .txt')
s_xx_1_FE_FE, s_xy_1_FE_FE, s_yy_1_FE_FE = np.loadtxt('sigma_xx2 ts=4.txt'), np.loadtxt('sigma_xy2 ts=4.txt'), np.loadtxt('sigma_yy2 ts=4.txt')
X_FE_FE, Y_FE_FE = np.loadtxt('X.txt'), np.loadtxt('Y.txt')
X1_FE_FE, Y1_FE_FE = np.loadtxt('X1.txt'), np.loadtxt('Y1.txt')
error_list_FE_FE = np.loadtxt('error_list_FE_NN_hyper ts=4 iter=23.txt')

os.chdir(originalDir_real)  

from scipy.spatial import KDTree
# create the target points array
target_points = np.column_stack((X1_NO, Y1_NO))
# create the source points array
source_points = np.column_stack((X1_FE, Y1_FE))

# create the KDTree for fast nearest neighbor search
tree = KDTree(source_points)
distances, index_XY1 = tree.query(target_points)

X1_FE = X1_FE[index_XY1]
Y1_FE = Y1_FE[index_XY1]
U1_FE = U1_FE[index_XY1]
V1_FE = V1_FE[index_XY1]
s_xx_1 = s_xx_1[index_XY1]
s_yy_1 = s_yy_1[index_XY1]
s_xy_1 = s_xy_1[index_XY1]




U_FE = Rbf(X_FE, Y_FE, U_FE)(X_FE_FE, Y_FE_FE)
V_FE = Rbf(X_FE, Y_FE, V_FE)(X_FE_FE, Y_FE_FE)

plot_relative_error(X1_FE, Y1_FE, np.abs(U1_NO -U1_FE), 'u_error_coupling_10_inner', rf'$|u_{{x, \mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - u_{{x, \mathrm{{FE-NO}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(V1_NO -V1_FE), 'v_error_coupling_10_inner', rf'$|u_{{y, \mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - u_{{y, \mathrm{{FE-NO}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(U1_FE_FE -U1_FE), 'u_error_FE_FE_coupling_10_inner', rf'$|u_{{x, \mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - u_{{x, \mathrm{{FE-FE}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(V1_FE_FE -V1_FE), 'v_error_FE_FE_coupling_10_inner', rf'$|u_{{y, \mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - u_{{y, \mathrm{{FE-FE}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X_FE_FE, Y_FE_FE, np.abs(U_NO -U_FE), 'u_error_coupling_10_full', rf'$|u_{{x, \mathrm{{FE}},\Omega_{{I}}}}^{{{4}}} - u_{{x, \mathrm{{FE-NO}},\Omega_{{I}}}}^{{{4}}}|$')
plot_relative_error(X_FE_FE, Y_FE_FE, np.abs(V_NO -V_FE), 'v_error_coupling_10_full', rf'$|u_{{y, \mathrm{{FE}},\Omega_{{I}}}}^{{{4}}} - u_{{y, \mathrm{{FE-NO}},\Omega_{{I}}}}^{{{4}}}|$')
plot_relative_error(X_FE_FE, Y_FE_FE, np.abs(U_FE_FE -U_FE), 'u_error_FE_FE_coupling_10_outer', rf'$|u_{{x, \mathrm{{FE}},\Omega_{{I}}}}^{{{4}}} - u_{{x, \mathrm{{FE-FE}},\Omega_{{I}}}}^{{{4}}}|$')
plot_relative_error(X_FE_FE, Y_FE_FE, np.abs(V_FE_FE -V_FE), 'v_error_FE_FE_coupling_10_outer', rf'$|u_{{y, \mathrm{{FE}},\Omega_{{I}}}}^{{{4}}} - u_{{y, \mathrm{{FE-FE}},\Omega_{{I}}}}^{{{4}}}|$')

#print('X1 difference', np.max(np.abs(X1_NO - X1_FE)), np.max(np.abs(X1_FE_FE - X1_FE)), np.max(np.abs(X1_FE_FE - X1_NO)))
#plot_disp(X1_FE, Y1_FE, s_xx_1_NO, 's_xx_NO_ground_truth_inner', rf'$\sigma_{{xx,\mathrm{{FE}},\Omega_{{II}}^{4}}}$')


plot_relative_error(X1_FE, Y1_FE, np.abs(s_xx_1_NO - s_xx_1), 's_xx_error_coupling_10_inner', rf'$|\sigma_{{xx,\mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - \sigma_{{xx,\mathrm{{FE-NO}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(s_yy_1_NO - s_yy_1), 's_yy_error_coupling_10_inner', rf'$|\sigma_{{yy,\mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - \sigma_{{yy,\mathrm{{FE-NO}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(s_xy_1_NO - s_xy_1), 's_xy_error_coupling_10_inner', rf'$|\sigma_{{xy,\mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - \sigma_{{xy,\mathrm{{FE-NO}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(s_xx_1_FE_FE - s_xx_1), 's_xx_error_FE_FE_coupling_10_inner', rf'$|\sigma_{{xx,\mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - \sigma_{{xx,\mathrm{{FE-FE}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(s_yy_1_FE_FE - s_yy_1), 's_yy_error_FE_FE_coupling_10_inner', rf'$|\sigma_{{yy,\mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - \sigma_{{yy,\mathrm{{FE-FE}},\Omega_{{II}}}}^{{{4}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(s_xy_1_FE_FE - s_xy_1), 's_xy_error_FE_FE_coupling_10_inner', rf'$|\sigma_{{xy,\mathrm{{FE}},\Omega_{{II}}}}^{{{4}}} - \sigma_{{xy,\mathrm{{FE-FE}},\Omega_{{II}}}}^{{{4}}}|$')

def plot_error_list(error_list1, error_list2, foldername):
    """
    Plots two error lists as line figures with a logarithmic scale on the y-axis.

    Parameters:
    error_list1 (list or array-like): First list of error values to plot (blue line).
    error_list2 (list or array-like): Second list of error values to plot (red line).
    foldername (str): Name of the file for saving the plot.
    """
    fig, ax = plt.subplots(figsize=(14, 8))
    
    # Plot the first error list
    ax.plot(
        np.linspace(1, error_list1.shape[0], error_list1.shape[0]), error_list1, marker='s', markersize=20, linestyle='-', linewidth=3, color='b', label='FE-NO'
    )
    
    # Plot the second error list
    ax.plot(
        np.linspace(1, error_list2.shape[0], error_list2.shape[0]), error_list2, marker='o', markersize=12, linestyle='--', linewidth=3, color='r', label='FE-FE'
    )

    # Adjust tick size and font size
    ax.tick_params(axis='both', which='major', labelsize=20, length=10, width=2)  # Major ticks
    ax.tick_params(axis='both', which='minor', labelsize=18, length=5, width=1)  # Minor ticks

    plt.yscale('log')
    #plt.title(foldername)
    plt.xlabel(r'inner iteration #', fontsize=24)
    plt.ylabel(r'$L_2$ error', fontsize=24)
    plt.xlim([0, len(error_list2)+1])
    # Add legends without border and place them in the upper right corner
    plt.legend(
        loc='upper right', bbox_to_anchor=(0.95, 1), frameon=False, fontsize=20
    )
    plt.grid(True)
    plt.savefig(foldername + ".jpg", dpi=700)
    plt.show()    


plot_error_list(error_list_FE_NO, error_list_FE_FE, 'MSE_error_comparison_static')
