import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import Rbf
from utils import plot_disp, plot_relative_error, createFolder

#region Save path       
originalDir = '/nfshdd/21040463r/FEM_DeepONet_non_overlapping_coupling/non_overlapping_static_clean'
print('current working directory is ' + originalDir)
os.chdir(os.path.join(originalDir))

foldername = 'FE_DeepONet_static_error_figures_previous'  
createFolder(foldername )
os.chdir(os.path.join(originalDir, './'+ foldername + '/')) 

originalDir_real = os.path.join(originalDir, './'+ foldername + '/')

os.chdir(os.path.join(originalDir, './'+ 'static_data_ground_truth_uv_001' + '/'))
# load the ground truth data generated by FEM in full sqaure 
U1_FE = np.loadtxt('u1.txt')
V1_FE = np.loadtxt('v1.txt')
U_FE, V_FE = np.loadtxt('u.txt'), np.loadtxt('v.txt')
e_xx_1, e_xy_1, e_yy_1 = np.loadtxt('strain_xx1.txt'), np.loadtxt('strain_xy1.txt'), np.loadtxt('strain_yy1.txt')
e_xx, e_xy, e_yy = np.loadtxt('strain_xx.txt'), np.loadtxt('strain_xy.txt'), np.loadtxt('strain_yy.txt')
X1_FE, Y1_FE = np.loadtxt('X1.txt'), np.loadtxt('Y1.txt')
X_FE, Y_FE = np.loadtxt('X.txt'), np.loadtxt('Y.txt')


os.chdir(os.path.join(originalDir, './'+ 'FE_DeepONet_static_non_overlapping_coupling_results' + '/'))

U1_NO, V1_NO = np.loadtxt('u2 i = 10 .txt'), np.loadtxt('v2 i = 10 .txt')
U_NO, V_NO = np.loadtxt('u i = 10 .txt'), np.loadtxt('v i = 10 .txt')
e_xx_1_NO, e_xy_1_NO, e_yy_1_NO = np.loadtxt('e_xx i = 10 .txt'), np.loadtxt('e_xy i = 10 .txt'), np.loadtxt('e_yy i = 10 .txt')
e_xx_NO, e_xy_NO, e_yy_NO = np.loadtxt('e_xx_outer i = 10 .txt'), np.loadtxt('e_xy_outer i = 10 .txt'), np.loadtxt('e_yy_outer i = 10 .txt')
X_NO, Y_NO = np.loadtxt('X.txt'), np.loadtxt('Y.txt')

os.chdir(originalDir_real)
plot_relative_error(X1_FE, Y1_FE, np.abs(U1_NO -U1_FE), 'u_error_coupling_10_inner', rf'$|u_{{x, \mathrm{{FE}},\Omega_{{II}}}} - u_{{x, \mathrm{{FE-NO}},\Omega_{{II}}}}^{{{10}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(V1_NO -V1_FE), 'v_error_coupling_10_inner', rf'$|u_{{y, \mathrm{{FE}},\Omega_{{II}}}} - u_{{y, \mathrm{{FE-NO}},\Omega_{{II}}}}^{{{10}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(e_xx_1_NO - e_xx_1), 'e_xx_error_coupling_10_inner', rf'$|\epsilon_{{xx,\mathrm{{FE}},\Omega_{{II}}}} - \epsilon_{{xx,\mathrm{{FE-NO}},\Omega_{{II}}}}^{{{10}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(e_yy_1_NO - e_yy_1), 'e_yy_error_coupling_10_inner', rf'$|\epsilon_{{yy,\mathrm{{FE}},\Omega_{{II}}}} - \epsilon_{{yy,\mathrm{{FE-NO}},\Omega_{{II}}}}^{{{10}}}|$')
plot_relative_error(X1_FE, Y1_FE, np.abs(e_xy_1_NO - e_xy_1), 'e_xy_error_coupling_10_inner', rf'$|\epsilon_{{xy,\mathrm{{FE}},\Omega_{{II}}}} - \epsilon_{{xy,\mathrm{{FE-NO}},\Omega_{{II}}}}^{{{10}}}|$')

'''U_FE_func = Rbf(X_FE, Y_FE, U_FE)
V_FE_func = Rbf(X_FE, Y_FE, V_FE)
e_xx_func, e_xy_func, e_yy_func = Rbf(X_FE, Y_FE, e_xx), Rbf(X_FE, Y_FE, e_xy), Rbf(X_FE, Y_FE, e_yy)
U_FE_out = U_FE_func(X_NO, Y_NO)
V_FE_out = V_FE_func(X_NO, Y_NO)
e_xx_FE_out = e_xx_func(X_NO, Y_NO)
e_yy_FE_out = e_yy_func(X_NO, Y_NO)
e_xy_FE_out = e_xy_func(X_NO, Y_NO)

np.savetxt('u_error_10_outer.txt', np.abs(U_NO - U_FE_out))
np.savetxt('v_error_10_outer.txt', np.abs(V_NO - V_FE_out))
np.savetxt('e_xx_error_10_outer.txt', np.abs(e_xx_FE_out - e_xx_NO))
np.savetxt('e_yy_error_10_outer.txt', np.abs(e_yy_FE_out - e_yy_NO))
np.savetxt('e_xy_error_10_outer.txt', np.abs(e_xy_FE_out - e_xy_NO))'''

u_error_10_outer = np.loadtxt('u_error_10_outer.txt')
v_error_10_outer = np.loadtxt('v_error_10_outer.txt')
e_xx_error_10_outer = np.loadtxt('e_xx_error_10_outer.txt')
e_yy_error_10_outer = np.loadtxt('e_yy_error_10_outer.txt')
e_xy_error_10_outer = np.loadtxt('e_xy_error_10_outer.txt')

plot_relative_error(X_NO, Y_NO, u_error_10_outer, 'u_error_coupling_10_outer', rf'$|u_{{x, \mathrm{{FE}},\Omega_{{I}}}} - u_{{x, \mathrm{{FE-NO}},\Omega_{{I}}}}^{{{10}}}|$')
plot_relative_error(X_NO, Y_NO, v_error_10_outer, 'v_error_coupling_10_outer', rf'$|u_{{y, \mathrm{{FE}},\Omega_{{I}}}} - u_{{y, \mathrm{{FE-NO}},\Omega_{{I}}}}^{{{10}}}|$')
plot_relative_error(X_NO, Y_NO, e_xx_error_10_outer, 'e_xx_error_coupling_10_outer', rf'$|\epsilon_{{xx,\mathrm{{FE}},\Omega_{{I}}}} - \epsilon_{{xx,\mathrm{{FE-NO}},\Omega_{{I}}}}^{{{10}}}|$')
plot_relative_error(X_NO, Y_NO, e_yy_error_10_outer, 'e_yy_error_coupling_10_outer', rf'$|\epsilon_{{yy,\mathrm{{FE}},\Omega_{{I}}}} - \epsilon_{{yy,\mathrm{{FE-NO}},\Omega_{{I}}}}^{{{10}}}|$')
plot_relative_error(X_NO, Y_NO, e_xy_error_10_outer, 'e_xy_error_coupling_10_outer', rf'$|\epsilon_{{xy,\mathrm{{FE}},\Omega_{{I}}}} - \epsilon_{{xy,\mathrm{{FE-NO}},\Omega_{{I}}}}^{{{10}}}|$')